version: "3.7"
services:
  mongo:
    container_name: climatempo_mongo
    image: mongo:latest
    restart: always
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: climatempo_db
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - mongo-compose-network 
  mongo-express:
    image: mongo-express
    restart: always
    ports:
        - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      MONGO_SERVER: climatempo_mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo
    networks:
      - mongo-compose-network
    depends_on:
      - mongo
  api:
    build: "./api"
    container_name: climatempo-api
    restart: always
    volumes:
      - ./api:/home/node/app
    ports:
      - "8082:8082"
    depends_on:
      - mongo-express
  app:
    build: "./app"
    container_name: climatempo-app
    restart: always
    volumes:
      - ./website:/var/www/html
    ports:
      - "3000:3000"
    depends_on:
      - api
volumes:
  mongodb:
  mongoconfig:
networks:
  mongo-compose-network:
    driver: bridge
